export enum PublicMessage {
    SendOtp = "کد با موفقیت ارسال شد.",
    LogedIn = "خوش آمدید",
    Created = "با موفقیت ایجاد شد",
    Deleted = "با موفقیت حذف شد",
    Updated = "با موفقیت بروزرسانی شد",
    Inserted = "با موفقیت اضافه شد",
    Liked = "مقاله به علاقهمندی ها پیوست",
    DisLiked = "مقاله از علاقهمندی ها پاک شد",
    AddToBookmarks = "مقاله ذخیره شد",
    RemoveFromBookmarks = "مقاله از لیست ذخیره ها پاک شد",
    CommentCreated = "نظر شما با موفقیت ثبت شد",
    RemoveComment = "نظر شما با موفقیت حذف شد",
    Followed = "كاربر با موفقيت دنبال شد",
    Unfollowed = "شما اين كاربر را فالو نميكنيد",
}